# Generated by Django 3.2.18 on 2023-03-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
            ],
            options={
                'verbose_name': 'mini course',
                'verbose_name_plural': 'mini courses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='name')),
                ('last_name', models.CharField(max_length=64, verbose_name='surname')),
                ('parent_phone', models.CharField(max_length=32, verbose_name='parent pthone')),
                ('is_presence', models.BooleanField(default=False, verbose_name='presence')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiapp.minicours')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
    ]
